name       : openastro
version    : 1.1.56
release    : 19
source     :
    - http://ppa.launchpad.net/pellesimon/ubuntu/pool/main/o/openastro.org/openastro.org_1.1.56.orig.tar.gz : b4b4fec697a52d2b19c8e69ab4d25165e7985d4e9cc42feea33ca80ee982e2cf
license    : GPL-3.0-or-later
component  : desktop
summary    : Open source fully-featured astrology software
description: |
    Open source fully-featured astrology software
rundeps    :
    - imagemagick
    - librsvg
    - openastro-data
    - pyswisseph
    - python3-cairo
    - python-dateutil
    - python-gobject
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
