name       : openastro
version    : 1.1.48
release    : 2
source     :
    - http://ppa.launchpad.net/pellesimon/ubuntu/pool/main/o/openastro.org/openastro.org_1.1.48.orig.tar.gz : 504fe7fa224ef66f3be2752593b7bfde84c7b599c5f26733f6093b55bf2a5b2a
license    : GPL-3.0
component  : desktop
summary    : Open source fully-featured astrology software
description: |
    Open source fully-featured astrology software
rundeps    :
    - gnome-python
    - gnome-python-desktop
    - imagemagick
    - librsvg
    - openastro-data
    - pyswisseph
    - python-cairo
    - python-dateutil
    - python-devel
    - python-gtk2
    - python-pytz
build      : |
    %python_setup
install    : |
    %python_install
