name       : openastro
version    : 1.1.57
release    : 9
source     :
    - http://ppa.launchpad.net/pellesimon/ubuntu/pool/main/o/openastro.org/openastro.org_1.1.57.orig.tar.gz : fd5431a76b0628142a24e21cbf458d47ee2667bfcd4437d50edecfc885c1543c
license    : GPL-3.0-or-later
component  : desktop
summary    : Open source fully-featured astrology software
description: |
    Open source fully-featured astrology software
rundeps    :
    - imagemagick
    - librsvg
    - openastro-data
    - pyswisseph
    - python3-cairo
    - python3-gobject
    - python-dateutil
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
